agents:
  provider: gcp
  image: family/kibana-ubuntu-2004
  imageProject: elastic-images-prod

env:
  ELASTIC_PR_COMMENTS_ENABLED: 'true'

steps:
  - command: .buildkite/scripts/lifecycle/pre_build.sh
    label: Pre-Build
    timeout_in_minutes: 10
    agents:
      machineType: n2-standard-2
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - command: |
      buildkite-agent meta-data set pr_comment:job_url "PR Project deployment started at: $BUILDKITE_BUILD_URL"'
    label: Comment with job URL
    agents:
      machineType: n2-standard-2
    timeout_in_minutes: 5

  - wait: ~

  - command: .buildkite/scripts/steps/artifacts/docker_image.sh
    label: 'Build Project Image'
    key: build_project_image
    agents:
      machineType: n2-standard-16
      preemptible: true
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3

  - wait: ~

  - command: .buildkite/scripts/steps/serverless/deploy.sh
    label: 'Deploy Project'
    agents:
      machineType: n2-standard-4
      preemptible: true
    timeout_in_minutes: 10
