steps:
  - command: .buildkite/scripts/steps/artifacts/docker_image.sh
    label: 'Build Project Image'
    agents:
      diskSizeGb: 50
      imagePrefix: kibana-ubuntu-2004-1717679530
      imageProject: elastic-images-qa
      provider: gcp
      machineType: n2-standard-16
      preemptible: true
    timeout_in_minutes: 60
    soft_fail: true
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
