steps:
  - command: .buildkite/scripts/steps/next_docs/build_and_validate_docs.sh
    label: 'Build and Validate Next Docs'
    agents:
      queue:
        provider: gcp
        preemptible: true
        image: family/kibana-ubuntu-2004
        imageProject: elastic-images-qa
        machineType: n2-standard-4
    timeout_in_minutes: 30
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
