steps:
  - command: .buildkite/scripts/steps/cloud/build_and_deploy.sh
    label: 'Build and Deploy to Cloud'
    agents:
      diskSizeGb: 50
      imagePrefix: kibana-ubuntu-2004-1717495844
      imageProject: elastic-images-qa
      provider: gcp
      machineType: n2-standard-2
      preemptible: true
    depends_on:
      - build
      - quick_checks
    timeout_in_minutes: 30
    soft_fail: true
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
