steps:
  - command: .buildkite/scripts/steps/cloud/build_and_deploy.sh
    label: 'Build and Deploy to Cloud'
    agents:
      queue:
        provider: gcp
        preemptible: true
        image: family/kibana-ubuntu-2004
        imageProject: elastic-images-qa
        machineType: n2-standard-2
        buildDirectory: /dev/shm/bk
    depends_on: build
    timeout_in_minutes: 30
    soft_fail: true
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
