steps:
  - command: .buildkite/scripts/steps/functional/exploratory_view_plugin.sh
    label: 'Exploratory View @elastic/synthetics Tests'
    agents:
      diskSizeGb: 50
      imagePrefix: kibana-ubuntu-2004-1717669216
      imageProject: elastic-images-qa
      provider: gcp
      machineType: n2-standard-4
      preemptible: true
    depends_on:
      - build
      - quick_checks
    timeout_in_minutes: 60
    artifact_paths:
      - 'x-pack/plugins/observability_solution/exploratory_view/e2e/.journeys/**/*'
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
        - exit_status: '*'
          limit: 1
