steps:
  - command: .buildkite/scripts/steps/test/kbn_handlebars.sh
    label: 'Check @kbn/handlebars for upstream differences'
    agents:
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-2
      preemptible: true
      assignExternalIP: false
    depends_on: build
    timeout_in_minutes: 5
    retry:
      automatic:
        - exit_status: '*'
          limit: 1
