steps:
  - wait: ~
    continue_on_failure: true

  - command: .buildkite/scripts/lifecycle/post_build.sh
    label: Post-Build
    agents:
      diskSizeGb: 50
      imagePrefix: kibana-ubuntu-2004-1717669216
      imageProject: elastic-images-qa
      provider: gcp
      machineType: n2-standard-2
