steps:
  - command: .buildkite/scripts/steps/functional/response_ops_cases.sh
    label: 'Cases Cypress Tests on Security Solution'
    agents:
      diskSizeGb: 50
      imagePrefix: kibana-ubuntu-2004-1717495844
      imageProject: elastic-images-qa
      provider: gcp
      machineType: n2-standard-4
      preemptible: true
    depends_on:
      - build
      - quick_checks
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: '*'
          limit: 1
