steps:
  - command: .buildkite/scripts/steps/functional/response_ops.sh
    label: 'Rules, Alerts and Exceptions ResponseOps Cypress Tests on Security Solution'
    agents:
      queue:
        provider: gcp
        preemptible: true
        image: family/kibana-ubuntu-2004
        imageProject: elastic-images-qa
        machineType: n2-standard-4
        buildDirectory: /dev/shm/bk
    depends_on: build
    timeout_in_minutes: 120
    parallelism: 4
    retry:
      automatic:
        - exit_status: '*'
          limit: 1
