steps:
  - command: .buildkite/scripts/steps/storybooks/build_and_upload.sh
    label: 'Build Storybooks'
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-8
      preemptible: true
      buildDirectory: /dev/shm/builds
    key: storybooks
    timeout_in_minutes: 80
