steps:
  - command: .buildkite/scripts/steps/check_types.sh
    label: 'Check Types'
    agents:
      queue:
        provider: gcp
        preemptible: true
        image: family/kibana-ubuntu-2004
        imageProject: elastic-images-qa
        machineType: n2-standard-16
        buildDirectory: /dev/shm/bk
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
