steps:
  - command: .buildkite/scripts/steps/webpack_bundle_analyzer/build_and_upload.sh
    label: 'Build Webpack Bundle Analyzer reports'
    agents:
      diskSizeGb: 50
      imagePrefix: kibana-ubuntu-2004-1717679530
      imageProject: elastic-images-qa
      provider: gcp
      machineType: n2-standard-4
      preemptible: true
    key: webpack_bundle_analyzer
    timeout_in_minutes: 60
