steps:
  - command: .buildkite/scripts/steps/webpack_bundle_analyzer/build_and_upload.sh
    label: 'Build Webpack Bundle Analyzer reports'
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-4
      preemptible: true
    key: webpack_bundle_analyzer
    timeout_in_minutes: 60
