steps:
  - command: .buildkite/scripts/steps/functional/security_serverless_ai_assistant.sh
    label: 'Serverless AI Assistant - Security Solution Cypress Tests'
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-4
      preemptible: true
    depends_on: build
    timeout_in_minutes: 60
    parallelism: 1
    retry:
      automatic:
        - exit_status: '*'
          limit: 1        

  - command: .buildkite/scripts/steps/functional/security_solution_ai_assistant.sh
    label: 'AI Assistant - Security Solution Cypress Tests'
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-4
      preemptible: true
    depends_on: build
    timeout_in_minutes: 60
    parallelism: 1
    retry:
      automatic:
        - exit_status: '*'
          limit: 1        
