steps:
  - command: .buildkite/scripts/steps/functional/defend_workflows.sh
    label: 'Defend Workflows Cypress Tests'
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      enableNestedVirtualization: true
      localSsds: 1
      machineType: n2-standard-4
      assignExternalIP: false
    depends_on:
      - build
      - quick_checks
    timeout_in_minutes: 60
    parallelism: 16
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - command: .buildkite/scripts/steps/functional/defend_workflows_serverless.sh
    label: 'Defend Workflows Cypress Tests on Serverless'
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      enableNestedVirtualization: true
      localSsds: 1
      machineType: n2-standard-4
      assignExternalIP: false
    depends_on:
      - build
      - quick_checks
    timeout_in_minutes: 60
    parallelism: 10
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  # status_exception: Native role management is not enabled in this Elasticsearch instance
  # - command: .buildkite/scripts/steps/functional/security_serverless_defend_workflows.sh
  #   label: 'Serverless Security Defend Workflows Cypress Tests'
  #   agents:
  #     queue: n2-4-spot
  #   depends_on: build
  #   timeout_in_minutes: 60
  #   retry:
  #     automatic:
  #       - exit_status: '*'
  #         limit: 1
