steps:
  - command: .buildkite/scripts/steps/functional/security_serverless_entity_analytics.sh
    label: 'Serverless Entity Analytics - Security Cypress Tests'
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-4
      preemptible: true
    depends_on:
      - build
      - quick_checks
    timeout_in_minutes: 60
    parallelism: 2
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - command: .buildkite/scripts/steps/functional/security_solution_entity_analytics.sh
    label: 'Entity Analytics - Security Solution Cypress Tests'
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-4
      preemptible: true
    depends_on:
      - build
      - quick_checks
    timeout_in_minutes: 60
    parallelism: 2
    retry:
      automatic:
        - exit_status: '*'
          limit: 1
