steps:
  - label: '👨‍🔧 Pre-Build'
    command: .buildkite/scripts/lifecycle/pre_build.sh
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-2
      assignExternalIP: false

  - wait

  - label: '🧑‍🏭 Build Kibana Distribution and Plugins'
    command: .buildkite/scripts/steps/build_kibana.sh
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: c2-standard-16
      buildDirectory: /dev/shm/builds
      assignExternalIP: false
    key: build
    if: "build.env('KIBANA_BUILD_ID') == null || build.env('KIBANA_BUILD_ID') == ''"

  - label: '💪 Performance Tests with Playwright config'
    command: .buildkite/scripts/steps/functional/performance_playwright.sh
    env:
      PERFORMANCE_ENABLE_TELEMETRY: true
    agents:
      queue: kb-static-ubuntu
    depends_on: build
    key: tests
    timeout_in_minutes: 90
    retry:
      automatic:
        - exit_status: '-1'
          limit: 2
        - exit_status: '*'
          limit: 1

  - label: '📈 Report performance metrics to ci-stats'
    command: .buildkite/scripts/steps/functional/report_performance_metrics.sh
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      localSsds: 1
      machineType: n2-standard-2
      assignExternalIP: false
    depends_on: tests

  - wait: ~
    continue_on_failure: true

  - label: '🦸 Post-Build'
    command: .buildkite/scripts/lifecycle/post_build.sh
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-2
      assignExternalIP: false
