steps:
  - label: ':male-mechanic::skin-tone-2: Pre-Build'
    command: .buildkite/scripts/lifecycle/pre_build.sh
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-2
      assignExternalIP: false
    timeout_in_minutes: 10

  - wait

  - label: ':building_construction: Build Kibana Distribution and Plugins'
    command: .buildkite/scripts/steps/build_kibana.sh
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: c2-standard-16
      buildDirectory: /dev/shm/builds
      assignExternalIP: false
    key: build
    if: "build.env('KIBANA_BUILD_ID') == null || build.env('KIBANA_BUILD_ID') == ''"

  - label: ':kibana: Performance Tests with Playwright config'
    command: .buildkite/scripts/steps/functional/performance_playwright.sh
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-2
      preemptible: true
      assignExternalIP: false
    depends_on: build
    key: tests
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
        - exit_status: '*'
          limit: 1

  - label: ':ship: Single user journeys dataset extraction for scalability benchmarking'
    command: .buildkite/scripts/steps/functional/scalability_dataset_extraction.sh
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      localSsds: 1
      machineType: n2-standard-2
      assignExternalIP: false
    depends_on: tests

  - wait: ~
    continue_on_failure: true

  - label: ':male_superhero::skin-tone-2: Post-Build'
    command: .buildkite/scripts/lifecycle/post_build.sh
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-2
      assignExternalIP: false
