$schema: https://moonrepo.dev/schemas/project.json

fileGroups:
  sharedGlobals: []
  default:
  - '**/*'
  production: []

tasks:
  greet:
    deps:
      - ^:greet
    script: echo "Hello from $MOON_PROJECT_ROOT!"
  jest:
    description: Run jest tests
    command: node
    options:
      runFromWorkspaceRoot: true
      mergeArgs: append
    args:
      - scripts/jest.js
      - '--passWithNoTests'
  jestCI:
    description: Run jest tests (in band)
    command: node
    options:
      runFromWorkspaceRoot: true
      mergeArgs: append
    args:
      - scripts/jest.js
      - '--passWithNoTests'
      - '--runInBand'
  lint:
    script: |
      cd $MOON_WORKSPACE_ROOT && node scripts/eslint.js $MOON_PROJECT_ROOT --no-error-on-unmatched-pattern
    deps: []
    inputs:
      # Source and test files
      - 'src/**/*'
      - 'tests/**/*'
      # Other config files
      - '*.config.*'
      # Project configs, any format, any depth
      - '**/.eslintrc.*'
      # Root configs, any format
      - '/.eslintignore'
      - '/.eslintrc.*'
  lint_with_types:
    options:
      runFromWorkspaceRoot: true
    command: node
    args:
      - $workspaceRoot/scripts/eslint_with_types.js
      - '--project'
      - $projectRoot/tsconfig.json
    env:
      NODE_OPTIONS: '--max-old-space-size=8192'
  genTypecheckConfig:
    script: "node $workspaceRoot/scripts/type_check.js --project $projectRoot/tsconfig.json --config-only"
    inputs:
      - "tsconfig.json"
    outputs:
      - "tsconfig.moon.json"
  typecheck:
    command:
      - 'tsc'
      - '--build'
      - '$projectRoot/tsconfig.moon.json'
      - '--pretty'
    inputs:
      - '@group(src)'
      - 'tsconfig.json'
      - 'tsconfig.*.json'
    outputs:
      - 'target'
    deps:
      - '@kbn/ts-type-check-cli:generateAllTypecheckConfigs'
      - '^:typecheck'
    options:
      runFromWorkspaceRoot: true
    env:
      NODE_OPTIONS: '--max-old-space-size=8192'

  env:
    script: env
  ping:
    script: cd $MOON_WORKSPACE_ROOT && echo $MOON_PROJECT_ID >> ping.log
