$schema: https://moonrepo.dev/schemas/project.json
id: '@kbn/serverless-storybook-config'
type: unknown
owners:
  defaultOwner: '@elastic/appex-sharedux'
toolchain:
  default: node
language: typescript
project:
  name: '@kbn/serverless-storybook-config'
  description: Moon project for @kbn/serverless-storybook-config
  channel: ''
  owner: '@elastic/appex-sharedux'
  metadata:
    sourceRoot: src/platform/packages/shared/serverless/storybook/config
tags:
  - platform
  - shared-common
  - dev
fileGroups:
  src:
    - '**/*.ts'
    - '!target/**/*'
tasks:
  jest:
    script: echo 'stubbed:noop'
  jestCI:
    script: echo 'stubbed:noop'
