steps:
  - command: .buildkite/scripts/steps/es_snapshots/build.sh
    label: Build ES Snapshot
    timeout_in_minutes: 30
    agents:
      queue:
        provider: gcp
        preemptible: true
        image: family/kibana-ubuntu-2004
        imageProject: elastic-images-qa
        machineType: c2-standard-8
        buildDirectory: /dev/shm/bk
