steps:
  - command: .buildkite/scripts/steps/es_snapshots/build.sh
    label: Build ES Snapshot
    timeout_in_minutes: 30
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      localSsds: 1
      machineType: c2-standard-8
      assignExternalIP: false
