steps:
  - command: .buildkite/scripts/steps/artifacts/trigger.sh
    label: Trigger artifacts build
    agents:
      provider: gcp
      preemptible: true
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-2
    timeout_in_minutes: 10
