steps:
  - command: .buildkite/scripts/steps/artifacts/docker_image.sh
    label: Build serverless container images
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-16
      preemptible: true
      buildDirectory: /dev/shm/builds
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
