env:
  PUBLISH_API_DOCS_CHANGES: 'true'
steps:
  - command: .buildkite/scripts/steps/build_api_docs.sh
    label: 'Build API Docs'
    agents:
      queue:
        provider: gcp
        preemptible: true
        image: family/kibana-ubuntu-2004
        imageProject: elastic-images-qa
        machineType: n2-standard-4
    key: build_api_docs
    timeout_in_minutes: 60
    retry:
      automatic:
        - exit_status: '-1'
          limit: 3
