steps:
  - command: .buildkite/scripts/steps/package_testing/build.sh
    label: Build Packages
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: c2-standard-16
      buildPath: /dev/shm/builds
    timeout_in_minutes: 60
    if: "build.env('KIBANA_BUILD_ID') == null || build.env('KIBANA_BUILD_ID') == ''"

  - wait

  - command: TEST_PACKAGE=deb .buildkite/scripts/steps/package_testing/test.sh
    label: Package testing for deb
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-4
    timeout_in_minutes: 60

  - command: TEST_PACKAGE=rpm .buildkite/scripts/steps/package_testing/test.sh
    label: Package testing for rpm
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-4
    timeout_in_minutes: 60

  - command: TEST_PACKAGE=docker .buildkite/scripts/steps/package_testing/test.sh
    label: Package testing for docker
    agents:
      provider: gcp
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-4
    timeout_in_minutes: 60
