steps:
  - command: .buildkite/scripts/steps/cloud/purge_deployments.sh
    label: Purge old cloud deployments
    timeout_in_minutes: 10
    agents:
      provider: gcp
      preemptible: true
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      machineType: n2-standard-2
