steps:
  - command: .buildkite/scripts/steps/demo_env/es_and_init.sh
    label: Initialize Environment and Deploy ES
    timeout_in_minutes: 10
    agents:
      queue:
        provider: gcp
        preemptible: true
        image: family/kibana-ubuntu-2004
        imageProject: elastic-images-qa
        machineType: n2-standard-2

  - command: .buildkite/scripts/steps/demo_env/kibana.sh
    label: Build and Deploy Kibana
    agents:
      queue:
        provider: gcp
        preemptible: true
        image: family/kibana-ubuntu-2004
        imageProject: elastic-images-qa
        machineType: c2-standard-8
    timeout_in_minutes: 60
